name: CI / CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * 5'
  
jobs:
  Build:
    name: Build
    uses: ./.github/workflows/build.yml
    secrets: inherit 
    #https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idsecretsinherit

  SCA:
    needs: Build
    name: SCA
    uses: ./.github/workflows/SCA.yml
    secrets: inherit

  SAST:
    needs: Build
    name: SAST
    uses: ./.github/workflows/SAST.yml
    secrets: inherit

  IAC:
    needs: Build
    name: KICKS
    uses: ./.github/workflows/IAC.yml
    secrets: inherit


  dast:
    needs: Build
    name: DAST Scan
    uses: ./.github/workflows/dast.yml
    secrets: inherit
 
