name: CI / CD Pipeline

on:
  workflow_call:
  
jobs:
  Build:
    name: Build
    uses: ./.github/workflows/build.yml
    secrets: inherit 
    #https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idsecretsinherit

  SCA:
    needs: Build
    name: SCA
    uses: ./.github/workflows/SCA.yml
    secrets: inherit

  SAST:
    needs: Build
    name: SAST
    uses: ./.github/workflows/SAST.yml
    secrets: inherit

  IAC:
    needs: Build
    name: KICKS
    uses: ./.github/workflows/IAC.yml
    secrets: inherit

  DAST:
    needs: Build
    name: DAST Scan
    uses: ./.github/workflows/dast.yml
    secrets: inherit
 
